### ISSUE TITLE
Parsing Issue with TORQUE

### ISSUE THREAD

**Issue by vtelezki** [glotzerlab/signac-flow#133]
### Description
After submitting jobs to our cluster, I am running into parsing issues when I try to run `status`. This issue does not happen when no job is running.
To clarify: The submitted job and jobs of other users are running.

### To reproduce
1) submit job to scheduler:
    `python3 project.py submit -o sample -n 1 -w 1`
2) check status while running:
    `python3 project.py status -d`

### Error Output
results in following error (with traceback)
```
Traceback (most recent call last):
  File "src/project.py", line 188, in <module>
    Project().main()
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 2721, in main
    _exit_or_raise()
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 2689, in main
    args.func(args)
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 2362, in _main_status
    self.print_status(jobs=jobs, **args)
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/legacy.py", line 230, in wrapper
    return func(self, jobs=jobs, *args, **kwargs)
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 1105, in print_status
    tmp = self._fetch_status(jobs, err, ignore_errors, no_parallelize)
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 994, in _fetch_status
    self._fetch_scheduler_status(jobs, err, ignore_errors)
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 975, in _fetch_scheduler_status
    scheduler_info = {sjob.name(): sjob.status() for sjob in self.scheduler_jobs(scheduler)}
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 975, in <dictcomp>
    scheduler_info = {sjob.name(): sjob.status() for sjob in self.scheduler_jobs(scheduler)}
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 856, in scheduler_jobs
    for sjob in self._expand_bundled_jobs(scheduler.jobs()):
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 832, in _expand_bundled_jobs
    for job in scheduler_jobs:
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/scheduling/torque.py", line 99, in jobs
    nodes = _fetch(user=self.user)
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/scheduling/torque.py", line 31, in _fetch
    tree = ET.parse(source=result)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 2, column 0
```
### Other outputs
Since the output of `qstat -fx -u $USER` is parsed, here the output (starting with a blank line):
```
pbs-goegrid.local: 
                                                                         Req'd  Req'd   Elap
Job ID               Username Queue    Jobname          SessID NDS   TSK Memory Time  S Time
-------------------- -------- -------- ---------------- ------ ----- --- ------ ----- - -----
52454128.pbs-goe     telezki  shorttim MTB/8f49762b/sam  14425     1   1    1gb 02:00 R 00:33
```

### System configuration

- Linux-2.6.32-754.14.2.el6.x86_64-x86_64-with-centos-6.10-Final
- 3.6.3 (default, Apr 26 2018, 13:16:02) 
- [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
- 1.2.0
- 0.7.1

**Comment by vtelezki** [comment]
This issue is not restricted to the `status` command. If I want to submit more jobs while my other job is running, I get a similar error output:
```
Using environment configuration: DefaultTorqueEnvironment
ERROR: Encountered error during program execution: 'syntax error: line 2, column 0'
Execute with '--show-traceback' or '--debug' to get more information.
Traceback (most recent call last):
  File "src/project.py", line 188, in <module>
    Project().main()
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 2721, in main
    _exit_or_raise()
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 2689, in main
    args.func(args)
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 2454, in _main_submit
    self._fetch_scheduler_status(jobs)
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 975, in _fetch_scheduler_status
    scheduler_info = {sjob.name(): sjob.status() for sjob in self.scheduler_jobs(scheduler)}
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 975, in <dictcomp>
    scheduler_info = {sjob.name(): sjob.status() for sjob in self.scheduler_jobs(scheduler)}
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 856, in scheduler_jobs
    for sjob in self._expand_bundled_jobs(scheduler.jobs()):
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/project.py", line 832, in _expand_bundled_jobs
    for job in scheduler_jobs:
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/scheduling/torque.py", line 99, in jobs
    nodes = _fetch(user=self.user)
  File "/home/telezki/Hoomd/venv/lib/python3.6/site-packages/flow/scheduling/torque.py", line 31, in _fetch
    tree = ET.parse(source=result)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 2, column 0
```

When no job was submitted, `python3 project.py status -d` gives the following warning:
```
Using environment configuration: DefaultTorqueEnvironment
WARNING:flow.scheduling.torque:No scheduler jobs, from any user(s), were detected. This may be the result of a misconfiguration in the environment.
Query scheduler...
```
Might the error be a result of this warning? Do I have to reconfigure the environment?

**Comment by bdice** [comment]
@vtelezki To debug this, we would need to get the raw XML response from your scheduler. It's a parsing error of whatever data the scheduler is giving back to signac-flow.

Following the steps from a similar parsing issue (#92), please copy/paste the output of `$ qstat -fx -u $USER`. That's the command signac-flow is calling to get XML output from the scheduler which is parsed into the status display.

**Comment by vtelezki** [comment]
@bdice, output of `qstat -fx -u $USER` is in the report under "Other outputs". Thanks for your help!

**Comment by bdice** [comment]
Hey @vtelezki, it looks like your cluster's version of PBS isn't giving XML output. See if you can read the manual for your version of PBS and identify if there's a flag for XML output. It can probably be found in `man qstat`.

For example, when I run `qstat -fx -u $USER` on our PBS scheduler, I get the following (when no jobs are running, so it's empty):

```xml
<?xml version="1.0"?>
<Data></Data>
```

We're running the following versions of PBS:

```bash
$ qstat --version
Version: 6.0.4
Commit: 6a0b37f85c7d644e9217cbab1542792d646f59a6
```

**Comment by vtelezki** [comment]
hey @bdice, the man page says the following: 
```
-x        Specifies  that  the  output is to be displayed in XML form.  This option is
                 only valid with the -f option or by itself, which will also specify  the  -f
                 full status display
```
It sounds to me that `-x` is incompatible with `-u`.  Running `qstat -fx -u $USER` returns nothing when no jobs are running. 

We are apparently running version 2.5.9. Might this be the issue?

**Comment by bdice** [comment]
@vtelezki It's possible that your scheduler is too old, or configured improperly. I'm guessing from the `git blame` that version 2.5.9 is about 8 years old (see below). If you look at issue #92, there have been some issues with XML output in a newer version (4.2.9) as well. I would recommend reaching out to your cluster's IT staff for assistance, they might upgrade things if you ask nicely. 😄

@glotzerlab/signac-developers Do we have a way to determine our minimum requirements for PBS scheduler versions? Any other potential causes or ideas to solve this?

----------------

https://github.com/adaptivecomputing/torque/blame/master/CHANGELOG

![image](https://user-images.githubusercontent.com/3943761/62369697-6888cf00-b4fe-11e9-8169-2827b3768c1e.png)

**Comment by vtelezki** [comment]
Ok. wow. I will  try my best. Wish me luck :stuck_out_tongue_closed_eyes: 
I will keep you updated, thank you for your help!

**Comment by csadorf** [comment]
@vtelezki This is what the output looks like for me on a different TORQUE system:
```
 $ qstat -fx -u $USER
<?xml version="1.0"?>
<Data></Data>
```
I don't have any jobs submitted on the system, but the command returns a valid XML document, which is what signac-flow is trying to parse. That appears to not be the case on your system.

This is odd, because that's what the `-x` flag is supposed to do, from the `qstat` man-page:
```
        -x        Specifies that the output is to be displayed in XML form.  This option is only valid with the -f option or by itself, which will also specify the -f  full
                 status display.
```
Can you double check whether the `-x` flag is supported by your scheduling system? That is something you could ask your IT support as well. I'm surprised that the command does not fail with `-x`.

**Comment by csadorf** [comment]
@vtelezki Were you able to determine what the issue with the `qstat` command might be?

**Comment by csadorf** [comment]
@vtelezki I'll close this for now, feel free to re-open if you need assistance again.
