### ISSUE TITLE
.bundle file not found when running python project.py status

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac-flow#34]
**[Original report](https://bitbucket.org/glotzer/signac-flow/issue/34) by RoseCers (Bitbucket: [RoseCers](https://bitbucket.org/RoseCers), ).**

----------------------------------------

```bash
Traceback (most recent call last):
  File "../../../job_scripts/project.py", line 108, in <module>
    Project().main()
  File "/home/rosecers/.local/lib/python3.5/site-packages/flow/project.py", line 2785, in main
    _exit_or_raise()
  File "/home/rosecers/.local/lib/python3.5/site-packages/flow/project.py", line 2754, in main
    args.func(args)
  File "/home/rosecers/.local/lib/python3.5/site-packages/flow/project.py", line 2428, in _main_status
    self.print_status(jobs=jobs, **args)
  File "/home/rosecers/.local/lib/python3.5/site-packages/flow/project.py", line 1141, in print_status
    self._fetch_scheduler_status(jobs, scheduler, err, ignore_errors)
  File "/home/rosecers/.local/lib/python3.5/site-packages/flow/project.py", line 1023, in _fetch_scheduler_status
    for sjob in self.scheduler_jobs(scheduler):
  File "/home/rosecers/.local/lib/python3.5/site-packages/flow/project.py", line 901, in scheduler_jobs
    for sjob in self._expand_bundled_jobs(scheduler.jobs()):
  File "/home/rosecers/.local/lib/python3.5/site-packages/flow/project.py", line 879, in _expand_bundled_jobs
    with open(self._fn_bundle(job.name())) as file:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/sglotzer1_fluxoe/***/.bundles/***/bundle/73f21***'
```

**Comment by csadorf** [comment]
There have not been any other reports of similar issues, I assume that this was an isolated case and will close for now.
