### ISSUE TITLE
Running signac-flow 0.16.0 with Python 3.10 results in "ImportError"

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac-flow#584]
### Description

I installed signac and signac-flow with conda with Python 3.10 and running any flow command results in a traceback with `ImportError`.

### To reproduce

Install signac and signac-flow and then run the `flow` command:

```console
conda create -n signac signac-flow
flow
```

### Error output

```python-traceback
$ flow
Traceback (most recent call last):
  File "/home/sadorf/miniconda3/envs/signac/bin/flow", line 6, in <module>
    from flow.__main__ import main
  File "/home/sadorf/miniconda3/envs/signac/lib/python3.10/site-packages/flow/__init__.py", line 11, in <module>
    from . import environment, errors, scheduling, testing
  File "/home/sadorf/miniconda3/envs/signac/lib/python3.10/site-packages/flow/environment.py", line 40, in <module>
    from .util import config as flow_config
  File "/home/sadorf/miniconda3/envs/signac/lib/python3.10/site-packages/flow/util/__init__.py", line 5, in <module>
    from . import misc, mistune, template_filters, translate
  File "/home/sadorf/miniconda3/envs/signac/lib/python3.10/site-packages/flow/util/mistune/__init__.py", line 4, in <module>
    from .renderers import AstRenderer, HTMLRenderer, TextRenderer, TerminalRenderer
  File "/home/sadorf/miniconda3/envs/signac/lib/python3.10/site-packages/flow/util/mistune/renderers.py", line 2, in <module>
    from .plugins.tabulate import tabulate
  File "/home/sadorf/miniconda3/envs/signac/lib/python3.10/site-packages/flow/util/mistune/plugins/tabulate.py", line 36, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/home/sadorf/miniconda3/envs/signac/lib/python3.10/collections/__init__.py)
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Ubuntu
 - Version of Python [e.g. 3.7]: 3.10
 - Version of signac [e.g. 1.0]: 1.7.0
 - Version of signac-flow: 0.16.0

**Comment by b-butler** [comment]
This is expected, as Python 3.10 support is currently only in the `master` branch. We would need to release a hot-fix or bug fix/minor release to add Python 3.10 support.

**Comment by csadorf** [comment]
> This is expected, as Python 3.10 support is currently only in the `master` branch. We would need to release a hot-fix or bug fix/minor release to add Python 3.10 support.

What is the timeline for this? The conda installation of signac-flow that is promoted in the documentation (literally the first command in the README) is currently broken which is a critical issue.

**Comment by bdice** [comment]
@csadorf There is currently no timeline for future releases. @b-butler Do you know who our release managers are supposed to be right now?

From my view of my the changelog, it looks like we could make a release at any time, we just need a volunteer. https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt @csadorf If you would like to make a release, that would be welcome. Let's coordinate in Slack to see if we have assigned release managers and proceed from there.

**Comment by csadorf** [comment]
Since this issue is already resolved, just not released, we can close this.
