### ISSUE TITLE
Incorrect command formatting in @flow.cmd

### ISSUE THREAD

**Issue by javierbg** [glotzerlab/signac-flow#630]
### Description

When testing the `@flow.cmd` operator I noticed something strange in the docs. The example code shows the following:
```python
@FlowProject.operation
@flow.cmd
def compute_volume(job):
    return "matlab -r 'prog {job.sp.foo} {job.sp.bar}' > {job.ws}/output.txt"
```
I noticed that the returned string is not an f-string, so whatever function calls `compute_volume` has the job of populating the command arguments.  That function is the `decorated()` function nested inside `flow.operations.with_job()`. The example works because both `decorated` and `compute_volume` name the job parameter `job`, but if I change the job parameter name for e.g. `j` and change the function to:
```python
@FlowProject.operation
@flow.cmd
def compute_volume(j):
    return "matlab -r 'prog {j.sp.foo} {j.sp.bar}' > {j.ws}/output.txt"
```
Then the code fails because `j` is not a local variable to `decorated`, although it would be difficult for a user to notice the problem from the traceback below.

I think the expected behavior of `@flow.cmd` is that the operation must return the full command already populated, as the user cannot know what the job parameter in the calling function is named (or, in that case, it should be documented). The example code should reflect that and return a fully formatted string (just adding an `f` right before the return value). Additionally, we should avoid the calling function from formatting the returned value, protecting it somehow.

I'm willing to implement and submit a fix but I wanted to know your opinions on how it should be resolved first.

### To reproduce

* Create a project and add a job (e.g. with statepoint `{"test_parameter": 1}`).
* Create a project file "project.py" containing the following:
```python
from flow import FlowProject
import flow

@FlowProject.operation
@flow.cmd
def testop(j):
  return 'echo "{j.sp.a}"'

if __name__ == '__main__':
  FlowProject().main()
```
* Run with traceback: `python project.py run --show-traceback`

Note that if the return value of `testop` is changed to `'echo "{job.sp.a}"'` (no need to change the name of the job parameter, mind you), the error disappears.

### Error output

The error traceback:
```
ERROR: Encountered error during program execution: ''j''

Traceback (most recent call last):
  File "/home/javierbg/miniconda3/envs/python39/lib/python3.9/site-packages/flow/project.py", line 4870, in main
    args.func(args)
  File "/home/javierbg/miniconda3/envs/python39/lib/python3.9/site-packages/flow/project.py", line 4550, in _main_run
    run()
  File "/home/javierbg/miniconda3/envs/python39/lib/python3.9/site-packages/flow/project.py", line 3438, in run
    self._run_operations(
  File "/home/javierbg/miniconda3/envs/python39/lib/python3.9/site-packages/flow/project.py", line 3058, in _run_operations
    self._execute_operation(operation, timeout, pretend)
  File "/home/javierbg/miniconda3/envs/python39/lib/python3.9/site-packages/flow/project.py", line 3179, in _execute_operation
    operation.cmd,
  File "/home/javierbg/miniconda3/envs/python39/lib/python3.9/site-packages/flow/project.py", line 356, in cmd
    return self._cmd()
  File "/home/javierbg/miniconda3/envs/python39/lib/python3.9/site-packages/flow/project.py", line 838, in _run_cmd
    return operation(*jobs).lstrip()
  File "/home/javierbg/miniconda3/envs/python39/lib/python3.9/site-packages/flow/project.py", line 576, in __call__
    return cmd.format(**format_arguments)
KeyError: 'j'
```

### System configuration

 - Operating System: Debian 10 (buster)
 - Version of Python: 3.9
 - Version of signac: 1.7.0
 - Version of signac-flow: 0.17.0

**Comment by bdice** [comment]
As a workaround, I think you can format the string yourself with `j` or any other variables before it is returned.

**Comment by javierbg** [comment]
I see, so the reason is that the `cmd` attribute of `FlowCmdOperation` might be a callable or just a `str`, which may need to be formatted.

I can see the rationale that most command operations could just be defined by a simple string that must be filled out with a couple of things. However, I see that the docs for `FlowCmdOperation` state that: "This class should not be instantiated directly". The only place where a `FlowCmdOperation` is instantiated is in `FlowProject._register_operations()`, where `cmd` is definitely a callable, but I just don't see how you would register such operation without instantiating `FlowCmdOperation` manually outside of `FlowProject._register_operations()`. Maybe `cmd` should always be a callable that is assumed to always return a fully formatted `str`?

In that case, `FlowCmdOperation.__call__(self, *jobs)` should just be:
```python
def __call__(self, *jobs): 
     """Return the command formatted with the supplied job(s).""" 
     return self._cmd(*jobs)
```
And of course the doc for `FlowCmdOperation` and the "Advanced How-To" section of the online documentation should be changed accordingly. Does this sound OK?

**Comment by javierbg** [comment]
> As a workaround, I think you can format the string yourself with `j` or any other variables before it is returned. Any remaining format fields for `{job}` would still be filled by flow.

Yes, for the time being I'm just doing this and everything works fine.

**Comment by cbkerr** [comment]
@kidrahahjo, @b-butler, and I discussed this issue ad its resolution #666 synchronously.

We decided to require the user to format the string themself, even when using `{job}`.

Your example would become
```python
@FlowProject.operation
@flow.cmd
def compute_volume(j):
    return f"matlab -r 'prog {j.sp.foo} {j.sp.bar}' > {j.ws}/output.txt"
```

In #666, we will go through a deprecation cycle for this change.

**Comment by b-butler** [comment]
@javierbg that is exactly what we are planning to do in the future to avoid problems like this.
