### ISSUE TITLE
PBS parse failure

### ISSUE THREAD

**Issue by mattwthompson** [glotzerlab/signac-flow#92]
### Description

When the output of a job status query (`squeue`, `qstat`, etc.) is completely empty instead of an empty node (`<Data></Data>`), the parser inside of `_fetch` fails and errors out.

### To reproduce

This happens on one of our clusters at Vanderbilt (running PBS 4.2.9) when no other users are running jobs, but the bug should reproducible whenever this behavior occurs:

```shell
$ echo $USER
mwt
$ qstat -fx -u $USER
$ qstat
```
Compared to the desired behavior (when somebody, not necessarily me, is running a job):
```
$ qstat -fx -u mwt # should be equivalent to qstat -fx -u $USER
<Data></Data>
```

I'm not sure why this happens, but it can be worked around via submitting a job that does anything, including sleeping:
```
$ qstat -fx -u $USER
$ qsub sleep.pbs 
39352.master.cl.vanderbilt.edu
$ qstat -fx -u $USER
<Data><Job><Job_Id>39352.master.cl.vanderbilt.edu</Job_Id><Job_Name>yep</Job_Name><Job_Owner>mwt@master.cl.vanderbilt.edu</Job_Owner><job_state>R</job_state><queue>low</queue><server>master.cl.vanderbilt.edu</server><Checkpoint>u</Checkpoint><ctime>1552875868</ctime><Error_Path>master.cl.vanderbilt.edu:/raid6/homes/mwt/science/sfg-on-quartz/yep.e39352</Error_Path><exec_host>node11/0+node11/1+node11/2+node11/3+node11/4+node11/5+node11/6+node11/7+node11/8+node11/9+node11/10+node11/11+node11/12+node11/13+node11/14+node11/15</exec_host><exec_port>15003+15003+15003+15003+15003+15003+15003+15003+15003+15003+15003+15003+15003+15003+15003+15003</exec_port><Hold_Types>n</Hold_Types><Join_Path>oe</Join_Path><Keep_Files>n</Keep_Files><Mail_Points>abe</Mail_Points><Mail_Users>mattwthomp@gmail.com</Mail_Users><mtime>1552875870</mtime><Output_Path>master.cl.vanderbilt.edu:/raid6/homes/mwt/science/sfg-on-quartz/yep.o39352</Output_Path><Priority>0</Priority><qtime>1552875868</qtime><Rerunable>True</Rerunable><Resource_List><ncpus>1</ncpus><nodect>1</nodect><nodes>1:ppn=16</nodes><walltime>48:00:00</walltime></Resource_List><session_id>23248</session_id><Variable_List>PBS_O_QUEUE=low,PBS_O_HOME=/raid6/homes/mwt,PBS_O_LOGNAME=mwt,PBS_O_PATH=/raid6/homes/mwt/software/anaconda/envs/mosdef/bin:/raid6/homes/mwt/software/anaconda/bin:/raid6/homes/mwt/software/anaconda/bin:/usr/lib64/qt-3.3/bin:/usr/local/mpi/gcc/openmpi-1.8.5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/cuda/bin:/raid6/homes/mwt/.local/bin:/raid6/homes/mwt/bin,PBS_O_MAIL=/var/spool/mail/mwt,PBS_O_SHELL=/bin/bash,PBS_O_LANG=en_US.UTF-8,PBS_O_WORKDIR=/raid6/homes/mwt/science/sfg-on-quartz,PBS_O_HOST=master.cl.vanderbilt.edu,PBS_O_SERVER=master,GMX_MAXBACKUP=10000000000,MANPATH=/usr/local/mpi/gcc/openmpi-1.8.5/share/man:,XDG_SESSION_ID=9851,HOSTNAME=master.cl.vanderbilt.edu,TERM=xterm-256color,SHELL=/bin/bash,HISTSIZE=1000,SSH_CLIENT=129.59.37.54 54191 22,QTDIR=/usr/lib64/qt-3.3,OLDPWD=/raid6/homes/mwt,QTINC=/usr/lib64/qt-3.3/include,SSH_TTY=/dev/pts/0,QT_GRAPHICSSYSTEM_CHECKED=1,USER=mwt,LD_LIBRARY_PATH=/usr/local/mpi/gcc/openmpi-1.8.5/lib64,LS_COLORS=rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:,MODULE_VERSION=3.2.10,MAIL=/var/spool/mail/mwt,PATH=/raid6/homes/mwt/software/anaconda/envs/mosdef/bin:/raid6/homes/mwt/software/anaconda/bin:/raid6/homes/mwt/software/anaconda/bin:/usr/lib64/qt-3.3/bin:/usr/local/mpi/gcc/openmpi-1.8.5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/cuda/bin:/raid6/homes/mwt/.local/bin:/raid6/homes/mwt/bin,CONDA_PATH_BACKUP=/raid6/homes/mwt/software/anaconda/bin:/raid6/homes/mwt/software/anaconda/bin:/usr/lib64/qt-3.3/bin:/usr/local/mpi/gcc/openmpi-1.8.5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/cuda/bin:/raid6/homes/mwt/.local/bin:/raid6/homes/mwt/bin,CONDA_PREFIX=/raid6/homes/mwt/software/anaconda/envs/mosdef,PWD=/raid6/homes/mwt/science/sfg-on-quartz,LANG=en_US.UTF-8,MODULEPATH=/raid6/software/Modules/3.2.10/modulefiles,KDEDIRS=/usr,PS1=(mosdef) [\\u@\\h \\W]\\$,HISTCONTROL=ignoredups,SHLVL=1,HOME=/raid6/homes/mwt,CONDA_PS1_BACKUP=[\\u@\\h \\W]\\$,MPI_ROOT=/usr/local/mpi/gcc/openmpi-1.8.5,LOGNAME=mwt,QTLIB=/usr/lib64/qt-3.3/lib,XDG_DATA_DIRS=/raid6/homes/mwt/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share,SSH_CONNECTION=129.59.37.54 54191 129.59.37.59 22,CONDA_DEFAULT_ENV=mosdef,LESSOPEN=||/usr/bin/lesspipe.sh %s,XDG_RUNTIME_DIR=/run/user/1011,QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins,_=/usr/local/bin/qsub</Variable_List><euser>mwt</euser><egroup>mwt</egroup><queue_type>E</queue_type><etime>1552875868</etime><submit_args>sleep.pbs</submit_args><start_time>1552875870</start_time><Walltime><Remaining>172800</Remaining></Walltime><start_count>1</start_count><fault_tolerant>False</fault_tolerant><job_radix>0</job_radix><submit_host>master.cl.vanderbilt.edu</submit_host></Job></Data>
```
I'm pretty sure if somebody else submitted a sleep job instead of me, it would be the `<Data></Data>` output above.
### Error output

```
$ python project.py status --debug
/raid6/homes/mwt/software/anaconda/envs/mosdef/lib/python3.5/site-packages/MDAnalysis/due.py:88: UserWarning: No module named 'mock'
  warnings.warn(str(err))
Query scheduler...
ERROR:flow.project:Error occured during status update. Use '--ignore-errors' to complete the update anyways or '--debug' to show the full traceback.
Traceback (most recent call last):
  File "project.py", line 319, in <module>
    SFGProject().main()
  File "/raid6/homes/mwt/software/anaconda/envs/mosdef/lib/python3.5/site-packages/flow/project.py", line 2796, in main
    _exit_or_raise()
  File "/raid6/homes/mwt/software/anaconda/envs/mosdef/lib/python3.5/site-packages/flow/project.py", line 2765, in main
    args.func(args)
  File "/raid6/homes/mwt/software/anaconda/envs/mosdef/lib/python3.5/site-packages/flow/project.py", line 2427, in _main_status
    self.print_status(jobs=jobs, **args)
  File "/raid6/homes/mwt/software/anaconda/envs/mosdef/lib/python3.5/site-packages/flow/project.py", line 1141, in print_status
    self._fetch_scheduler_status(jobs, scheduler, err, ignore_errors)
  File "/raid6/homes/mwt/software/anaconda/envs/mosdef/lib/python3.5/site-packages/flow/project.py", line 1023, in _fetch_scheduler_status
    for sjob in self.scheduler_jobs(scheduler):
  File "/raid6/homes/mwt/software/anaconda/envs/mosdef/lib/python3.5/site-packages/flow/project.py", line 901, in scheduler_jobs
    for sjob in self._expand_bundled_jobs(scheduler.jobs()):
  File "/raid6/homes/mwt/software/anaconda/envs/mosdef/lib/python3.5/site-packages/flow/project.py", line 877, in _expand_bundled_jobs
    for job in scheduler_jobs:
  File "/raid6/homes/mwt/software/anaconda/envs/mosdef/lib/python3.5/site-packages/flow/scheduling/torque.py", line 86, in jobs
    nodes = _fetch(user=self.user)
  File "/raid6/homes/mwt/software/anaconda/envs/mosdef/lib/python3.5/site-packages/flow/scheduling/torque.py", line 33, in _fetch
    tree = ET.parse(source=result)
  File "/raid6/homes/mwt/software/anaconda/envs/mosdef/lib/python3.5/xml/etree/ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "/raid6/homes/mwt/software/anaconda/envs/mosdef/lib/python3.5/xml/etree/ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: CentOS

```lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core
```
 - Version of Python [e.g. 3.7]: Python 3.5.5
 - Version of signac [e.g. 1.0]: 0.9.5
 - Version of signac-flow: 0.6.3

Or copy & paste the output of: `python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac; print(signac.__version__); import flow; print(flow.__version__)'`
```
$ python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac; print(signac.__version__); import flow; print(flow.__version__)'
Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
0.9.5
0.6.3
```

**Comment by csadorf** [comment]
Resolved with merge of #93 .
